// <auto-generated />
using System;
using ClinicFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907074954_AddClinicsClinicDoctorsAndDiagnoses")]
    partial class AddClinicsClinicDoctorsAndDiagnoses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasDatabaseName("UX_Allergies_NameAr")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_Allergies_NameEn")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Allergies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(1194),
                            DescriptionAr = "حساسية تجاه المضادات الحيوية من نوع البنسلين",
                            DescriptionEn = "Allergy to penicillin antibiotics",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "البنسلين",
                            NameEn = "Penicillin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(1198),
                            DescriptionAr = "حساسية تجاه الأسبرين",
                            DescriptionEn = "Allergy to aspirin",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الأسبرين",
                            NameEn = "Aspirin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(1200),
                            DescriptionAr = "حساسية تجاه الإيبوبروفين",
                            DescriptionEn = "Allergy to ibuprofen",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الإيبوبروفين",
                            NameEn = "Ibuprofen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(1201),
                            DescriptionAr = "حساسية تجاه مادة اللاتكس",
                            DescriptionEn = "Allergy to latex",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "اللاتكس",
                            NameEn = "Latex"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(1202),
                            DescriptionAr = "حساسية تجاه الفول السوداني",
                            DescriptionEn = "Allergy to peanuts",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الفول السوداني",
                            NameEn = "Peanuts"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(1205),
                            DescriptionAr = "حساسية تجاه الحليب أو منتجات الألبان",
                            DescriptionEn = "Allergy to milk or dairy products",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الحليب",
                            NameEn = "Milk"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(1207),
                            DescriptionAr = "حساسية تجاه البيض",
                            DescriptionEn = "Allergy to eggs",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "البيض",
                            NameEn = "Eggs"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(1208),
                            DescriptionAr = "حساسية تجاه المحار",
                            DescriptionEn = "Allergy to shellfish",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "المحار",
                            NameEn = "Shellfish"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.ChronicCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasDatabaseName("UX_ChronicConditions_NameAr")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_ChronicConditions_NameEn")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ChronicConditions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(5511),
                            DescriptionAr = "اضطراب أيضي يتميز بارتفاع مستوى سكر الدم",
                            DescriptionEn = "A metabolic disorder characterized by elevated blood glucose levels",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "داء السكري",
                            NameEn = "Diabetes Mellitus"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(5519),
                            DescriptionAr = "ارتفاع مستمر في ضغط الدم",
                            DescriptionEn = "Persistently elevated blood pressure",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ارتفاع ضغط الدم",
                            NameEn = "Hypertension"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(5521),
                            DescriptionAr = "حالة تنفسية مزمنة تؤثر على الشعب الهوائية",
                            DescriptionEn = "A chronic respiratory condition affecting the airways",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الربو",
                            NameEn = "Asthma"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(5522),
                            DescriptionAr = "ضعف طويل الأمد في وظائف الكلى",
                            DescriptionEn = "Long-term impairment of kidney function",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مرض الكلى المزمن",
                            NameEn = "Chronic Kidney Disease"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(5524),
                            DescriptionAr = "حالة مزمنة تؤثر على القلب",
                            DescriptionEn = "A chronic condition affecting the heart",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "أمراض القلب",
                            NameEn = "Heart Disease"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(5528),
                            DescriptionAr = "اضطراب يؤثر على وظائف الغدة الدرقية",
                            DescriptionEn = "A disorder affecting thyroid function",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "اضطراب الغدة الدرقية",
                            NameEn = "Thyroid Disorder"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 276, DateTimeKind.Utc).AddTicks(5530),
                            DescriptionAr = "مرض رئوي مزمن يسبب محدودية تدفق الهواء",
                            DescriptionEn = "A chronic lung disease causing airflow limitation",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مرض الانسداد الرئوي المزمن",
                            NameEn = "Chronic Obstructive Pulmonary Disease"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clinics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 277, DateTimeKind.Utc).AddTicks(2172),
                            DescriptionAr = "تشخيص وعلاج أمراض الباطنة لدى البالغين.",
                            DescriptionEn = "Diagnosis and treatment of adult internal medicine conditions.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "عيادة الباطنة",
                            NameEn = "Internal Medicine Clinic"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 277, DateTimeKind.Utc).AddTicks(2181),
                            DescriptionAr = "تشخيص وعلاج أمراض القلب والأوعية الدموية.",
                            DescriptionEn = "Diagnosis and treatment of cardiovascular diseases.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "عيادة القلب",
                            NameEn = "Cardiology Clinic"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 277, DateTimeKind.Utc).AddTicks(2183),
                            DescriptionAr = "الرعاية الطبية للرضع والأطفال والمراهقين.",
                            DescriptionEn = "Medical care for infants, children, and adolescents.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "عيادة الأطفال",
                            NameEn = "Pediatric Clinic"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 277, DateTimeKind.Utc).AddTicks(2184),
                            DescriptionAr = "تشخيص وعلاج أمراض الأسنان والفم.",
                            DescriptionEn = "Diagnosis and treatment of dental and oral conditions.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "عيادة الأسنان",
                            NameEn = "Dental Clinic"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 277, DateTimeKind.Utc).AddTicks(2186),
                            DescriptionAr = "تشخيص وعلاج أمراض الجلد والشعر والأظافر.",
                            DescriptionEn = "Diagnosis and treatment of skin, hair, and nail conditions.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "عيادة الجلدية",
                            NameEn = "Dermatology Clinic"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 277, DateTimeKind.Utc).AddTicks(2190),
                            DescriptionAr = "تشخيص وعلاج أمراض الأنف والأذن والحنجرة.",
                            DescriptionEn = "Diagnosis and treatment of ear, nose, and throat conditions.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "عيادة الأنف والأذن والحنجرة",
                            NameEn = "ENT Clinic"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 277, DateTimeKind.Utc).AddTicks(2191),
                            DescriptionAr = "تشخيص وعلاج أمراض العيون ومشاكل النظر.",
                            DescriptionEn = "Diagnosis and treatment of eye and vision conditions.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "عيادة العيون",
                            NameEn = "Ophthalmology Clinic"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 277, DateTimeKind.Utc).AddTicks(2193),
                            DescriptionAr = "الرعاية الأولية للحالات الطبية الشائعة.",
                            DescriptionEn = "Primary care for common medical conditions.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "عيادة الطب العام",
                            NameEn = "General Practice Clinic"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.ClinicDoctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId", "ClinicId")
                        .IsUnique()
                        .HasDatabaseName("UX_ClinicDoctors_Doctor_Clinic")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ClinicDoctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 278, DateTimeKind.Utc).AddTicks(2056),
                            DoctorId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 278, DateTimeKind.Utc).AddTicks(2061),
                            DoctorId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 278, DateTimeKind.Utc).AddTicks(2062),
                            DoctorId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            ClinicId = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 278, DateTimeKind.Utc).AddTicks(2063),
                            DoctorId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            ClinicId = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 278, DateTimeKind.Utc).AddTicks(2064),
                            DoctorId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            ClinicId = 6,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 278, DateTimeKind.Utc).AddTicks(2066),
                            DoctorId = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            ClinicId = 8,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 278, DateTimeKind.Utc).AddTicks(2067),
                            DoctorId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            ClinicId = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 278, DateTimeKind.Utc).AddTicks(2068),
                            DoctorId = 2,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Diagnoses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3821),
                            DescriptionAr = "ارتفاع ضغط الدم الأساسي دون سبب ثانوي محدد.",
                            DescriptionEn = "Primary hypertension without a specified secondary cause.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ارتفاع ضغط الدم الأساسي",
                            NameEn = "Essential hypertension"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3828),
                            DescriptionAr = "داء السكري من النوع الثاني دون مضاعفات مسجلة.",
                            DescriptionEn = "Type 2 diabetes mellitus without documented complications.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "داء السكري من النوع الثاني دون مضاعفات",
                            NameEn = "Type 2 diabetes mellitus without complications"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3829),
                            DescriptionAr = "عدوى حادة في الجهاز التنفسي العلوي دون تحديد السبب.",
                            DescriptionEn = "Acute upper respiratory infection without a specified cause.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "عدوى الجهاز التنفسي العلوي الحادة غير المحددة",
                            NameEn = "Acute upper respiratory infection, unspecified"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3831),
                            DescriptionAr = "مرض الربو دون تحديد نوع أو تفاصيل إضافية.",
                            DescriptionEn = "Asthma without further specification.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الربو غير المحدد",
                            NameEn = "Asthma, unspecified"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3832),
                            DescriptionAr = "ارتفاع مستوى الدهون في الدم دون تحديد إضافي.",
                            DescriptionEn = "Elevated blood lipids without further specification.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "فرط شحميات الدم غير المحدد",
                            NameEn = "Hyperlipidemia, unspecified"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3836),
                            DescriptionAr = "مرض الارتجاع المعدي المريئي دون التهاب في المريء.",
                            DescriptionEn = "Gastro-esophageal reflux disease without esophagitis.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مرض الارتجاع المعدي المريئي دون التهاب المريء",
                            NameEn = "Gastro-esophageal reflux disease without esophagitis"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3837),
                            DescriptionAr = "ألم في منطقة أسفل الظهر.",
                            DescriptionEn = "Pain located in the lower back.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ألم أسفل الظهر",
                            NameEn = "Low back pain"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3838),
                            DescriptionAr = "الصداع النصفي دون تحديد إضافي.",
                            DescriptionEn = "Migraine without further specification.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الصداع النصفي غير المحدد",
                            NameEn = "Migraine, unspecified"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3840),
                            DescriptionAr = "التهاب رئوي دون تحديد الكائن المسبب.",
                            DescriptionEn = "Pneumonia without identification of the causative organism.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الالتهاب الرئوي غير المحدد",
                            NameEn = "Pneumonia, unspecified organism"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3842),
                            DescriptionAr = "التهاب في المسالك البولية دون تحديد الموقع.",
                            DescriptionEn = "Urinary tract infection without a specified site.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "التهاب المسالك البولية غير المحدد",
                            NameEn = "Urinary tract infection, site not specified"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3843),
                            DescriptionAr = "التهاب الجلد التأتبي دون تحديد إضافي.",
                            DescriptionEn = "Atopic dermatitis without further specification.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "التهاب الجلد التأتبي غير المحدد",
                            NameEn = "Atopic dermatitis, unspecified"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3844),
                            DescriptionAr = "التهاب ملتحمة العين دون تحديد إضافي.",
                            DescriptionEn = "Inflammation of the conjunctiva without further specification.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "التهاب الملتحمة غير المحدد",
                            NameEn = "Conjunctivitis, unspecified"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3845),
                            DescriptionAr = "التهاب بطانة المعدة دون تحديد إضافي.",
                            DescriptionEn = "Inflammation of the stomach lining without further specification.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "التهاب المعدة غير المحدد",
                            NameEn = "Gastritis, unspecified"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3846),
                            DescriptionAr = "فقر الدم دون تحديد نوعه.",
                            DescriptionEn = "Anemia without further specification.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "فقر الدم غير المحدد",
                            NameEn = "Anemia, unspecified"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(3847),
                            DescriptionAr = "قصور الغدة الدرقية دون تحديد إضافي.",
                            DescriptionEn = "Hypothyroidism without further specification.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "قصور الغدة الدرقية غير المحدد",
                            NameEn = "Hypothyroidism, unspecified"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsultationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsultationFee = 50.00m,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(8426),
                            Email = "ahmed.mohamed@clinic.com",
                            FullName = "Dr. Ahmed Mohamed",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 2,
                            ConsultationFee = 60.00m,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(8432),
                            Email = "sara.ali@clinic.com",
                            FullName = "Dr. Sara Ali",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0923456789"
                        },
                        new
                        {
                            Id = 3,
                            ConsultationFee = 45.00m,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(8434),
                            Email = "mohamed.hassan@clinic.com",
                            FullName = "Dr. Mohamed Hassan",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0934567890"
                        },
                        new
                        {
                            Id = 4,
                            ConsultationFee = 55.00m,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(8436),
                            Email = "fatima.ahmed@clinic.com",
                            FullName = "Dr. Fatima Ahmed",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0945678901"
                        },
                        new
                        {
                            Id = 5,
                            ConsultationFee = 50.00m,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(8437),
                            Email = "khalid.osman@clinic.com",
                            FullName = "Dr. Khalid Osman",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0956789012"
                        },
                        new
                        {
                            Id = 6,
                            ConsultationFee = 65.00m,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(8440),
                            Email = "huda.ibrahim@clinic.com",
                            FullName = "Dr. Huda Ibrahim",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0967890123"
                        },
                        new
                        {
                            Id = 7,
                            ConsultationFee = 50.00m,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(8441),
                            Email = "yousif.omar@clinic.com",
                            FullName = "Dr. Yousif Omar",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0978901234"
                        },
                        new
                        {
                            Id = 8,
                            ConsultationFee = 70.00m,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 280, DateTimeKind.Utc).AddTicks(8443),
                            Email = "maryam.ibrahim@clinic.com",
                            FullName = "Dr. Maryam Ibrahim",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0989012345"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.DoctorSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("DoctorId", "SpecialtyId")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorSpecialties_DoctorId_SpecialtyId")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("DoctorSpecialties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 281, DateTimeKind.Utc).AddTicks(4546),
                            DoctorId = 1,
                            IsDeleted = false,
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 281, DateTimeKind.Utc).AddTicks(4551),
                            DoctorId = 1,
                            IsDeleted = false,
                            SpecialtyId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 281, DateTimeKind.Utc).AddTicks(4552),
                            DoctorId = 2,
                            IsDeleted = false,
                            SpecialtyId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 281, DateTimeKind.Utc).AddTicks(4553),
                            DoctorId = 3,
                            IsDeleted = false,
                            SpecialtyId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 281, DateTimeKind.Utc).AddTicks(4553),
                            DoctorId = 3,
                            IsDeleted = false,
                            SpecialtyId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 281, DateTimeKind.Utc).AddTicks(4556),
                            DoctorId = 4,
                            IsDeleted = false,
                            SpecialtyId = 10
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 281, DateTimeKind.Utc).AddTicks(4557),
                            DoctorId = 5,
                            IsDeleted = false,
                            SpecialtyId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 281, DateTimeKind.Utc).AddTicks(4558),
                            DoctorId = 6,
                            IsDeleted = false,
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 281, DateTimeKind.Utc).AddTicks(4558),
                            DoctorId = 7,
                            IsDeleted = false,
                            SpecialtyId = 11
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 281, DateTimeKind.Utc).AddTicks(4560),
                            DoctorId = 8,
                            IsDeleted = false,
                            SpecialtyId = 8
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Patients_Email")
                        .HasFilter("[Email] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Patients_NationalId")
                        .HasFilter("[NationalId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_Patients_PhoneNumber")
                        .HasFilter("[PhoneNumber] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khartoum",
                            BloodType = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(1636),
                            DateOfBirth = new DateTime(1985, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "1234567890",
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Omdurman",
                            BloodType = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(1644),
                            DateOfBirth = new DateTime(1992, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.mohamed@example.com",
                            FullName = "Sara Mohamed",
                            Gender = 2,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "0987654321",
                            PhoneNumber = "0998765432"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bahri",
                            BloodType = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(1646),
                            DateOfBirth = new DateTime(1978, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed.ali@example.com",
                            FullName = "Mohamed Ali",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "1122334455",
                            PhoneNumber = "0911223344"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Khartoum",
                            BloodType = 6,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(1648),
                            DateOfBirth = new DateTime(2000, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima.ahmed@example.com",
                            FullName = "Fatima Ahmed",
                            Gender = 2,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "2233445566",
                            PhoneNumber = "0922334455"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Omdurman",
                            BloodType = 8,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(1680),
                            DateOfBirth = new DateTime(1969, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.ibrahim@example.com",
                            FullName = "Omar Ibrahim",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "3344556677",
                            PhoneNumber = "0933445566"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IdentifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.HasIndex("PatientId", "AllergyId")
                        .IsUnique()
                        .HasDatabaseName("UX_PatientAllergies_Patient_Allergy")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PatientAllergies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllergyId = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 282, DateTimeKind.Utc).AddTicks(1364),
                            IdentifiedAt = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Known penicillin allergy",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            AllergyId = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 282, DateTimeKind.Utc).AddTicks(1371),
                            IdentifiedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Avoid latex products",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 3,
                            AllergyId = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 282, DateTimeKind.Utc).AddTicks(1373),
                            IdentifiedAt = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Reported by patient",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 4,
                            AllergyId = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 282, DateTimeKind.Utc).AddTicks(1374),
                            IdentifiedAt = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Food allergy",
                            PatientId = 3
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientChronicCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChronicConditionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DiagnosedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChronicConditionId");

                    b.HasIndex("PatientId", "ChronicConditionId")
                        .IsUnique()
                        .HasDatabaseName("UX_PatientChronicConditions_Patient_Condition")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PatientChronicConditions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChronicConditionId = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 282, DateTimeKind.Utc).AddTicks(7518),
                            DiagnosedAt = new DateTime(2018, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Type 2 diabetes",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChronicConditionId = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 282, DateTimeKind.Utc).AddTicks(7525),
                            DiagnosedAt = new DateTime(2020, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Currently under treatment",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 3,
                            ChronicConditionId = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 282, DateTimeKind.Utc).AddTicks(7527),
                            DiagnosedAt = new DateTime(2016, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Intermittent asthma",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 4,
                            ChronicConditionId = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 282, DateTimeKind.Utc).AddTicks(7529),
                            DiagnosedAt = new DateTime(2019, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Regular blood pressure monitoring",
                            PatientId = 3
                        },
                        new
                        {
                            Id = 5,
                            ChronicConditionId = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 282, DateTimeKind.Utc).AddTicks(7531),
                            DiagnosedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Requires regular kidney function monitoring",
                            PatientId = 5
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Specialties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4756),
                            DescriptionAr = "تشخيص وعلاج أمراض القلب والأوعية الدموية",
                            DescriptionEn = "Diagnosis and treatment of heart and cardiovascular diseases",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "أمراض القلب",
                            NameEn = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4761),
                            DescriptionAr = "تشخيص وعلاج أمراض الجلد والشعر والأظافر",
                            DescriptionEn = "Diagnosis and treatment of skin, hair, and nail conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الأمراض الجلدية",
                            NameEn = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4762),
                            DescriptionAr = "الرعاية الطبية للرضع والأطفال والمراهقين",
                            DescriptionEn = "Medical care for infants, children, and adolescents",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "طب الأطفال",
                            NameEn = "Pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4764),
                            DescriptionAr = "تشخيص وعلاج الأمراض التي تصيب الأعضاء الداخلية",
                            DescriptionEn = "Diagnosis and treatment of diseases affecting internal organs",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الطب الباطني",
                            NameEn = "Internal Medicine"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4765),
                            DescriptionAr = "العلاج الجراحي لمجموعة واسعة من الحالات الطبية",
                            DescriptionEn = "Surgical treatment of a wide range of medical conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الجراحة العامة",
                            NameEn = "General Surgery"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4768),
                            DescriptionAr = "تشخيص وعلاج أمراض وإصابات الجهاز العضلي الهيكلي",
                            DescriptionEn = "Diagnosis and treatment of musculoskeletal conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "جراحة العظام",
                            NameEn = "Orthopedics"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4769),
                            DescriptionAr = "تشخيص وعلاج اضطرابات الجهاز العصبي",
                            DescriptionEn = "Diagnosis and treatment of disorders of the nervous system",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "طب الأعصاب",
                            NameEn = "Neurology"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4771),
                            DescriptionAr = "تشخيص وعلاج أمراض العيون واضطرابات الرؤية",
                            DescriptionEn = "Diagnosis and treatment of eye diseases and vision disorders",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "طب العيون",
                            NameEn = "Ophthalmology"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4772),
                            DescriptionAr = "الوقاية وتشخيص وعلاج أمراض الأسنان والفم",
                            DescriptionEn = "Prevention, diagnosis, and treatment of dental conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "طب الأسنان",
                            NameEn = "Dentistry"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4774),
                            DescriptionAr = "الرعاية الطبية المتعلقة بالحمل والولادة وصحة المرأة الإنجابية",
                            DescriptionEn = "Medical care related to pregnancy, childbirth, and women's reproductive health",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "النساء والتوليد",
                            NameEn = "Obstetrics and Gynecology"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4776),
                            DescriptionAr = "تشخيص وعلاج أمراض الأنف والأذن والحنجرة",
                            DescriptionEn = "Diagnosis and treatment of ear, nose, and throat conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الأنف والأذن والحنجرة",
                            NameEn = "ENT"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 9, 7, 7, 49, 52, 283, DateTimeKind.Utc).AddTicks(4777),
                            DescriptionAr = "تشخيص وعلاج اضطرابات الصحة النفسية",
                            DescriptionEn = "Diagnosis and treatment of mental health conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الطب النفسي",
                            NameEn = "Psychiatry"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.ClinicDoctor", b =>
                {
                    b.HasOne("ClinicFlow.Domain.Entities.Clinic", "Clinic")
                        .WithMany("ClinicDoctors")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Domain.Entities.Doctor", "Doctor")
                        .WithMany("ClinicDoctors")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.DoctorSpecialty", b =>
                {
                    b.HasOne("ClinicFlow.Domain.Entities.Doctor", "Doctor")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Domain.Entities.Specialty", "Specialty")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientAllergy", b =>
                {
                    b.HasOne("ClinicFlow.Domain.Entities.Allergy", "Allergy")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Domain.Entities.Patient", "Patient")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientChronicCondition", b =>
                {
                    b.HasOne("ClinicFlow.Domain.Entities.ChronicCondition", "ChronicCondition")
                        .WithMany("PatientChronicConditions")
                        .HasForeignKey("ChronicConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Domain.Entities.Patient", "Patient")
                        .WithMany("PatientChronicConditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChronicCondition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Allergy", b =>
                {
                    b.Navigation("PatientAllergies");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.ChronicCondition", b =>
                {
                    b.Navigation("PatientChronicConditions");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Clinic", b =>
                {
                    b.Navigation("ClinicDoctors");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("ClinicDoctors");

                    b.Navigation("DoctorSpecialties");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Patient", b =>
                {
                    b.Navigation("PatientAllergies");

                    b.Navigation("PatientChronicConditions");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("DoctorSpecialties");
                });
#pragma warning restore 612, 618
        }
    }
}
