// <auto-generated />
using System;
using ClinicFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905100233_AddDoctorsEntities")]
    partial class AddDoctorsEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasDatabaseName("UX_Allergies_NameAr")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_Allergies_NameEn")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Allergies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(4221),
                            DescriptionAr = "حساسية تجاه المضادات الحيوية من نوع البنسلين",
                            DescriptionEn = "Allergy to penicillin antibiotics",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "البنسلين",
                            NameEn = "Penicillin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(4226),
                            DescriptionAr = "حساسية تجاه الأسبرين",
                            DescriptionEn = "Allergy to aspirin",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الأسبرين",
                            NameEn = "Aspirin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(4228),
                            DescriptionAr = "حساسية تجاه الإيبوبروفين",
                            DescriptionEn = "Allergy to ibuprofen",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الإيبوبروفين",
                            NameEn = "Ibuprofen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(4230),
                            DescriptionAr = "حساسية تجاه مادة اللاتكس",
                            DescriptionEn = "Allergy to latex",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "اللاتكس",
                            NameEn = "Latex"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(4232),
                            DescriptionAr = "حساسية تجاه الفول السوداني",
                            DescriptionEn = "Allergy to peanuts",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الفول السوداني",
                            NameEn = "Peanuts"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(4235),
                            DescriptionAr = "حساسية تجاه الحليب أو منتجات الألبان",
                            DescriptionEn = "Allergy to milk or dairy products",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الحليب",
                            NameEn = "Milk"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(4237),
                            DescriptionAr = "حساسية تجاه البيض",
                            DescriptionEn = "Allergy to eggs",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "البيض",
                            NameEn = "Eggs"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(4238),
                            DescriptionAr = "حساسية تجاه المحار",
                            DescriptionEn = "Allergy to shellfish",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "المحار",
                            NameEn = "Shellfish"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.ChronicCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasDatabaseName("UX_ChronicConditions_NameAr")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_ChronicConditions_NameEn")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ChronicConditions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(9057),
                            DescriptionAr = "اضطراب أيضي يتميز بارتفاع مستوى سكر الدم",
                            DescriptionEn = "A metabolic disorder characterized by elevated blood glucose levels",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "داء السكري",
                            NameEn = "Diabetes Mellitus"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(9060),
                            DescriptionAr = "ارتفاع مستمر في ضغط الدم",
                            DescriptionEn = "Persistently elevated blood pressure",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ارتفاع ضغط الدم",
                            NameEn = "Hypertension"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(9061),
                            DescriptionAr = "حالة تنفسية مزمنة تؤثر على الشعب الهوائية",
                            DescriptionEn = "A chronic respiratory condition affecting the airways",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الربو",
                            NameEn = "Asthma"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(9063),
                            DescriptionAr = "ضعف طويل الأمد في وظائف الكلى",
                            DescriptionEn = "Long-term impairment of kidney function",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مرض الكلى المزمن",
                            NameEn = "Chronic Kidney Disease"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(9064),
                            DescriptionAr = "حالة مزمنة تؤثر على القلب",
                            DescriptionEn = "A chronic condition affecting the heart",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "أمراض القلب",
                            NameEn = "Heart Disease"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(9067),
                            DescriptionAr = "اضطراب يؤثر على وظائف الغدة الدرقية",
                            DescriptionEn = "A disorder affecting thyroid function",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "اضطراب الغدة الدرقية",
                            NameEn = "Thyroid Disorder"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 356, DateTimeKind.Utc).AddTicks(9068),
                            DescriptionAr = "مرض رئوي مزمن يسبب محدودية تدفق الهواء",
                            DescriptionEn = "A chronic lung disease causing airflow limitation",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مرض الانسداد الرئوي المزمن",
                            NameEn = "Chronic Obstructive Pulmonary Disease"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ConsultationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsultationFee = 50.00m,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(2011),
                            Email = "ahmed.mohamed@clinic.com",
                            FullName = "Dr. Ahmed Mohamed",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 2,
                            ConsultationFee = 60.00m,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(2016),
                            Email = "sara.ali@clinic.com",
                            FullName = "Dr. Sara Ali",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0923456789"
                        },
                        new
                        {
                            Id = 3,
                            ConsultationFee = 45.00m,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(2018),
                            Email = "mohamed.hassan@clinic.com",
                            FullName = "Dr. Mohamed Hassan",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0934567890"
                        },
                        new
                        {
                            Id = 4,
                            ConsultationFee = 55.00m,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(2019),
                            Email = "fatima.ahmed@clinic.com",
                            FullName = "Dr. Fatima Ahmed",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0945678901"
                        },
                        new
                        {
                            Id = 5,
                            ConsultationFee = 50.00m,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(2021),
                            Email = "khalid.osman@clinic.com",
                            FullName = "Dr. Khalid Osman",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0956789012"
                        },
                        new
                        {
                            Id = 6,
                            ConsultationFee = 65.00m,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(2024),
                            Email = "huda.ibrahim@clinic.com",
                            FullName = "Dr. Huda Ibrahim",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0967890123"
                        },
                        new
                        {
                            Id = 7,
                            ConsultationFee = 50.00m,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(2025),
                            Email = "yousif.omar@clinic.com",
                            FullName = "Dr. Yousif Omar",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0978901234"
                        },
                        new
                        {
                            Id = 8,
                            ConsultationFee = 70.00m,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(2027),
                            Email = "maryam.ibrahim@clinic.com",
                            FullName = "Dr. Maryam Ibrahim",
                            IsActive = true,
                            IsDeleted = false,
                            PhoneNumber = "0989012345"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.DoctorSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("DoctorId", "SpecialtyId")
                        .IsUnique()
                        .HasDatabaseName("UX_DoctorSpecialties_DoctorId_SpecialtyId")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("DoctorSpecialties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(7787),
                            DoctorId = 1,
                            IsDeleted = false,
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(7790),
                            DoctorId = 1,
                            IsDeleted = false,
                            SpecialtyId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(7791),
                            DoctorId = 2,
                            IsDeleted = false,
                            SpecialtyId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(7792),
                            DoctorId = 3,
                            IsDeleted = false,
                            SpecialtyId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(7793),
                            DoctorId = 3,
                            IsDeleted = false,
                            SpecialtyId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(7796),
                            DoctorId = 4,
                            IsDeleted = false,
                            SpecialtyId = 10
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(7796),
                            DoctorId = 5,
                            IsDeleted = false,
                            SpecialtyId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(7797),
                            DoctorId = 6,
                            IsDeleted = false,
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(7798),
                            DoctorId = 7,
                            IsDeleted = false,
                            SpecialtyId = 11
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 357, DateTimeKind.Utc).AddTicks(7800),
                            DoctorId = 8,
                            IsDeleted = false,
                            SpecialtyId = 8
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Patients_Email")
                        .HasFilter("[Email] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Patients_NationalId")
                        .HasFilter("[NationalId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_Patients_PhoneNumber")
                        .HasFilter("[PhoneNumber] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khartoum",
                            BloodType = 7,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(5581),
                            DateOfBirth = new DateTime(1985, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "1234567890",
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Omdurman",
                            BloodType = 1,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(5588),
                            DateOfBirth = new DateTime(1992, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.mohamed@example.com",
                            FullName = "Sara Mohamed",
                            Gender = 2,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "0987654321",
                            PhoneNumber = "0998765432"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bahri",
                            BloodType = 3,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(5590),
                            DateOfBirth = new DateTime(1978, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed.ali@example.com",
                            FullName = "Mohamed Ali",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "1122334455",
                            PhoneNumber = "0911223344"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Khartoum",
                            BloodType = 6,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(5592),
                            DateOfBirth = new DateTime(2000, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima.ahmed@example.com",
                            FullName = "Fatima Ahmed",
                            Gender = 2,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "2233445566",
                            PhoneNumber = "0922334455"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Omdurman",
                            BloodType = 8,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(5595),
                            DateOfBirth = new DateTime(1969, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.ibrahim@example.com",
                            FullName = "Omar Ibrahim",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "3344556677",
                            PhoneNumber = "0933445566"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IdentifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.HasIndex("PatientId", "AllergyId")
                        .IsUnique()
                        .HasDatabaseName("UX_PatientAllergies_Patient_Allergy")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PatientAllergies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllergyId = 1,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 358, DateTimeKind.Utc).AddTicks(4496),
                            IdentifiedAt = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Known penicillin allergy",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            AllergyId = 4,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 358, DateTimeKind.Utc).AddTicks(4503),
                            IdentifiedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Avoid latex products",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 3,
                            AllergyId = 2,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 358, DateTimeKind.Utc).AddTicks(4505),
                            IdentifiedAt = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Reported by patient",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 4,
                            AllergyId = 5,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 358, DateTimeKind.Utc).AddTicks(4506),
                            IdentifiedAt = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Food allergy",
                            PatientId = 3
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientChronicCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChronicConditionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DiagnosedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChronicConditionId");

                    b.HasIndex("PatientId", "ChronicConditionId")
                        .IsUnique()
                        .HasDatabaseName("UX_PatientChronicConditions_Patient_Condition")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PatientChronicConditions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChronicConditionId = 1,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(1410),
                            DiagnosedAt = new DateTime(2018, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Type 2 diabetes",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChronicConditionId = 2,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(1418),
                            DiagnosedAt = new DateTime(2020, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Currently under treatment",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 3,
                            ChronicConditionId = 3,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(1420),
                            DiagnosedAt = new DateTime(2016, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Intermittent asthma",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 4,
                            ChronicConditionId = 2,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(1422),
                            DiagnosedAt = new DateTime(2019, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Regular blood pressure monitoring",
                            PatientId = 3
                        },
                        new
                        {
                            Id = 5,
                            ChronicConditionId = 4,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(1423),
                            DiagnosedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Requires regular kidney function monitoring",
                            PatientId = 5
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Specialties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8245),
                            DescriptionAr = "تشخيص وعلاج أمراض القلب والأوعية الدموية",
                            DescriptionEn = "Diagnosis and treatment of heart and cardiovascular diseases",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "أمراض القلب",
                            NameEn = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8249),
                            DescriptionAr = "تشخيص وعلاج أمراض الجلد والشعر والأظافر",
                            DescriptionEn = "Diagnosis and treatment of skin, hair, and nail conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الأمراض الجلدية",
                            NameEn = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8250),
                            DescriptionAr = "الرعاية الطبية للرضع والأطفال والمراهقين",
                            DescriptionEn = "Medical care for infants, children, and adolescents",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "طب الأطفال",
                            NameEn = "Pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8252),
                            DescriptionAr = "تشخيص وعلاج الأمراض التي تصيب الأعضاء الداخلية",
                            DescriptionEn = "Diagnosis and treatment of diseases affecting internal organs",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الطب الباطني",
                            NameEn = "Internal Medicine"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8253),
                            DescriptionAr = "العلاج الجراحي لمجموعة واسعة من الحالات الطبية",
                            DescriptionEn = "Surgical treatment of a wide range of medical conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الجراحة العامة",
                            NameEn = "General Surgery"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8256),
                            DescriptionAr = "تشخيص وعلاج أمراض وإصابات الجهاز العضلي الهيكلي",
                            DescriptionEn = "Diagnosis and treatment of musculoskeletal conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "جراحة العظام",
                            NameEn = "Orthopedics"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8257),
                            DescriptionAr = "تشخيص وعلاج اضطرابات الجهاز العصبي",
                            DescriptionEn = "Diagnosis and treatment of disorders of the nervous system",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "طب الأعصاب",
                            NameEn = "Neurology"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8259),
                            DescriptionAr = "تشخيص وعلاج أمراض العيون واضطرابات الرؤية",
                            DescriptionEn = "Diagnosis and treatment of eye diseases and vision disorders",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "طب العيون",
                            NameEn = "Ophthalmology"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8260),
                            DescriptionAr = "الوقاية وتشخيص وعلاج أمراض الأسنان والفم",
                            DescriptionEn = "Prevention, diagnosis, and treatment of dental conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "طب الأسنان",
                            NameEn = "Dentistry"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8262),
                            DescriptionAr = "الرعاية الطبية المتعلقة بالحمل والولادة وصحة المرأة الإنجابية",
                            DescriptionEn = "Medical care related to pregnancy, childbirth, and women's reproductive health",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "النساء والتوليد",
                            NameEn = "Obstetrics and Gynecology"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8263),
                            DescriptionAr = "تشخيص وعلاج أمراض الأنف والأذن والحنجرة",
                            DescriptionEn = "Diagnosis and treatment of ear, nose, and throat conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الأنف والأذن والحنجرة",
                            NameEn = "ENT"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 2, 31, 359, DateTimeKind.Utc).AddTicks(8265),
                            DescriptionAr = "تشخيص وعلاج اضطرابات الصحة النفسية",
                            DescriptionEn = "Diagnosis and treatment of mental health conditions",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الطب النفسي",
                            NameEn = "Psychiatry"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.DoctorSpecialty", b =>
                {
                    b.HasOne("ClinicFlow.Domain.Entities.Doctor", "Doctor")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Domain.Entities.Specialty", "Specialty")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientAllergy", b =>
                {
                    b.HasOne("ClinicFlow.Domain.Entities.Allergy", "Allergy")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Domain.Entities.Patient", "Patient")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientChronicCondition", b =>
                {
                    b.HasOne("ClinicFlow.Domain.Entities.ChronicCondition", "ChronicCondition")
                        .WithMany("PatientChronicConditions")
                        .HasForeignKey("ChronicConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Domain.Entities.Patient", "Patient")
                        .WithMany("PatientChronicConditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChronicCondition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Allergy", b =>
                {
                    b.Navigation("PatientAllergies");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.ChronicCondition", b =>
                {
                    b.Navigation("PatientChronicConditions");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("DoctorSpecialties");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Patient", b =>
                {
                    b.Navigation("PatientAllergies");

                    b.Navigation("PatientChronicConditions");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("DoctorSpecialties");
                });
#pragma warning restore 612, 618
        }
    }
}
