// <auto-generated />
using System;
using ClinicFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831143001_AddPatientsEntities")]
    partial class AddPatientsEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasDatabaseName("UX_Allergies_NameAr")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_Allergies_NameEn")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Allergies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(102),
                            DescriptionAr = "حساسية تجاه المضادات الحيوية من نوع البنسلين",
                            DescriptionEn = "Allergy to penicillin antibiotics",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "البنسلين",
                            NameEn = "Penicillin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(107),
                            DescriptionAr = "حساسية تجاه الأسبرين",
                            DescriptionEn = "Allergy to aspirin",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الأسبرين",
                            NameEn = "Aspirin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(108),
                            DescriptionAr = "حساسية تجاه الإيبوبروفين",
                            DescriptionEn = "Allergy to ibuprofen",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الإيبوبروفين",
                            NameEn = "Ibuprofen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(109),
                            DescriptionAr = "حساسية تجاه مادة اللاتكس",
                            DescriptionEn = "Allergy to latex",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "اللاتكس",
                            NameEn = "Latex"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(111),
                            DescriptionAr = "حساسية تجاه الفول السوداني",
                            DescriptionEn = "Allergy to peanuts",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الفول السوداني",
                            NameEn = "Peanuts"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(116),
                            DescriptionAr = "حساسية تجاه الحليب أو منتجات الألبان",
                            DescriptionEn = "Allergy to milk or dairy products",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الحليب",
                            NameEn = "Milk"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(117),
                            DescriptionAr = "حساسية تجاه البيض",
                            DescriptionEn = "Allergy to eggs",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "البيض",
                            NameEn = "Eggs"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(118),
                            DescriptionAr = "حساسية تجاه المحار",
                            DescriptionEn = "Allergy to shellfish",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "المحار",
                            NameEn = "Shellfish"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.ChronicCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameAr")
                        .IsUnique()
                        .HasDatabaseName("UX_ChronicConditions_NameAr")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_ChronicConditions_NameEn")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ChronicConditions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(3697),
                            DescriptionAr = "اضطراب أيضي يتميز بارتفاع مستوى سكر الدم",
                            DescriptionEn = "A metabolic disorder characterized by elevated blood glucose levels",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "داء السكري",
                            NameEn = "Diabetes Mellitus"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(3701),
                            DescriptionAr = "ارتفاع مستمر في ضغط الدم",
                            DescriptionEn = "Persistently elevated blood pressure",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ارتفاع ضغط الدم",
                            NameEn = "Hypertension"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(3737),
                            DescriptionAr = "حالة تنفسية مزمنة تؤثر على الشعب الهوائية",
                            DescriptionEn = "A chronic respiratory condition affecting the airways",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "الربو",
                            NameEn = "Asthma"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(3738),
                            DescriptionAr = "ضعف طويل الأمد في وظائف الكلى",
                            DescriptionEn = "Long-term impairment of kidney function",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مرض الكلى المزمن",
                            NameEn = "Chronic Kidney Disease"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(3739),
                            DescriptionAr = "حالة مزمنة تؤثر على القلب",
                            DescriptionEn = "A chronic condition affecting the heart",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "أمراض القلب",
                            NameEn = "Heart Disease"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(3743),
                            DescriptionAr = "اضطراب يؤثر على وظائف الغدة الدرقية",
                            DescriptionEn = "A disorder affecting thyroid function",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "اضطراب الغدة الدرقية",
                            NameEn = "Thyroid Disorder"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(3744),
                            DescriptionAr = "مرض رئوي مزمن يسبب محدودية تدفق الهواء",
                            DescriptionEn = "A chronic lung disease causing airflow limitation",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "مرض الانسداد الرئوي المزمن",
                            NameEn = "Chronic Obstructive Pulmonary Disease"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Patients_Email")
                        .HasFilter("[Email] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Patients_NationalId")
                        .HasFilter("[NationalId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_Patients_PhoneNumber")
                        .HasFilter("[PhoneNumber] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khartoum",
                            BloodType = 7,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 38, DateTimeKind.Utc).AddTicks(8673),
                            DateOfBirth = new DateTime(1985, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "1234567890",
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Omdurman",
                            BloodType = 1,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 38, DateTimeKind.Utc).AddTicks(8679),
                            DateOfBirth = new DateTime(1992, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.mohamed@example.com",
                            FullName = "Sara Mohamed",
                            Gender = 2,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "0987654321",
                            PhoneNumber = "0998765432"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bahri",
                            BloodType = 3,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 38, DateTimeKind.Utc).AddTicks(8682),
                            DateOfBirth = new DateTime(1978, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed.ali@example.com",
                            FullName = "Mohamed Ali",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "1122334455",
                            PhoneNumber = "0911223344"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Khartoum",
                            BloodType = 6,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 38, DateTimeKind.Utc).AddTicks(8684),
                            DateOfBirth = new DateTime(2000, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima.ahmed@example.com",
                            FullName = "Fatima Ahmed",
                            Gender = 2,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "2233445566",
                            PhoneNumber = "0922334455"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Omdurman",
                            BloodType = 8,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 38, DateTimeKind.Utc).AddTicks(8686),
                            DateOfBirth = new DateTime(1969, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.ibrahim@example.com",
                            FullName = "Omar Ibrahim",
                            Gender = 1,
                            IsActive = true,
                            IsDeleted = false,
                            NationalId = "3344556677",
                            PhoneNumber = "0933445566"
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IdentifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.HasIndex("PatientId", "AllergyId")
                        .IsUnique()
                        .HasDatabaseName("UX_PatientAllergies_Patient_Allergy")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PatientAllergies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllergyId = 1,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(9168),
                            IdentifiedAt = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Known penicillin allergy",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            AllergyId = 4,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(9206),
                            IdentifiedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Avoid latex products",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 3,
                            AllergyId = 2,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(9208),
                            IdentifiedAt = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Reported by patient",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 4,
                            AllergyId = 5,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 37, DateTimeKind.Utc).AddTicks(9210),
                            IdentifiedAt = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Food allergy",
                            PatientId = 3
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientChronicCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChronicConditionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DiagnosedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChronicConditionId");

                    b.HasIndex("PatientId", "ChronicConditionId")
                        .IsUnique()
                        .HasDatabaseName("UX_PatientChronicConditions_Patient_Condition")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PatientChronicConditions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChronicConditionId = 1,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 38, DateTimeKind.Utc).AddTicks(4649),
                            DiagnosedAt = new DateTime(2018, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Type 2 diabetes",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChronicConditionId = 2,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 38, DateTimeKind.Utc).AddTicks(4655),
                            DiagnosedAt = new DateTime(2020, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Currently under treatment",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 3,
                            ChronicConditionId = 3,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 38, DateTimeKind.Utc).AddTicks(4657),
                            DiagnosedAt = new DateTime(2016, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Intermittent asthma",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 4,
                            ChronicConditionId = 2,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 38, DateTimeKind.Utc).AddTicks(4659),
                            DiagnosedAt = new DateTime(2019, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Regular blood pressure monitoring",
                            PatientId = 3
                        },
                        new
                        {
                            Id = 5,
                            ChronicConditionId = 4,
                            CreatedAt = new DateTime(2026, 8, 31, 14, 29, 59, 38, DateTimeKind.Utc).AddTicks(4660),
                            DiagnosedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Notes = "Requires regular kidney function monitoring",
                            PatientId = 5
                        });
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientAllergy", b =>
                {
                    b.HasOne("ClinicFlow.Domain.Entities.Allergy", "Allergy")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Domain.Entities.Patient", "Patient")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.PatientChronicCondition", b =>
                {
                    b.HasOne("ClinicFlow.Domain.Entities.ChronicCondition", "ChronicCondition")
                        .WithMany("PatientChronicConditions")
                        .HasForeignKey("ChronicConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicFlow.Domain.Entities.Patient", "Patient")
                        .WithMany("PatientChronicConditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChronicCondition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Allergy", b =>
                {
                    b.Navigation("PatientAllergies");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.ChronicCondition", b =>
                {
                    b.Navigation("PatientChronicConditions");
                });

            modelBuilder.Entity("ClinicFlow.Domain.Entities.Patient", b =>
                {
                    b.Navigation("PatientAllergies");

                    b.Navigation("PatientChronicConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
