//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicFlow.Domain.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClinicFlow.Domain.Resources.Shared.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB-.
        /// </summary>
        public static string ABNegative {
            get {
                return ResourceManager.GetString("ABNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB+.
        /// </summary>
        public static string ABPositive {
            get {
                return ResourceManager.GetString("ABPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies.
        /// </summary>
        public static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy.
        /// </summary>
        public static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        public static string ANegative {
            get {
                return ResourceManager.GetString("ANegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        public static string APositive {
            get {
                return ResourceManager.GetString("APositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-.
        /// </summary>
        public static string BNegative {
            get {
                return ResourceManager.GetString("BNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond Categories.
        /// </summary>
        public static string BondCategories {
            get {
                return ResourceManager.GetString("BondCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonds.
        /// </summary>
        public static string Bonds {
            get {
                return ResourceManager.GetString("Bonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B+.
        /// </summary>
        public static string BPositive {
            get {
                return ResourceManager.GetString("BPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic Condition.
        /// </summary>
        public static string ChronicCondition {
            get {
                return ResourceManager.GetString("ChronicCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic Conditions.
        /// </summary>
        public static string ChronicConditions {
            get {
                return ResourceManager.GetString("ChronicConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Description.
        /// </summary>
        public static string DescriptionAr {
            get {
                return ResourceManager.GetString("DescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description.
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosed At.
        /// </summary>
        public static string DiagnosedAt {
            get {
                return ResourceManager.GetString("DiagnosedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified At.
        /// </summary>
        public static string IdentifiedAt {
            get {
                return ResourceManager.GetString("IdentifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Status.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Entries.
        /// </summary>
        public static string JournalEntries {
            get {
                return ResourceManager.GetString("JournalEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Categories.
        /// </summary>
        public static string LabCategories {
            get {
                return ResourceManager.GetString("LabCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory.
        /// </summary>
        public static string Laboratory {
            get {
                return ResourceManager.GetString("Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Orders.
        /// </summary>
        public static string LabOrders {
            get {
                return ResourceManager.GetString("LabOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Results.
        /// </summary>
        public static string LabResults {
            get {
                return ResourceManager.GetString("LabResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Tests.
        /// </summary>
        public static string LabTests {
            get {
                return ResourceManager.GetString("LabTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string NationalId {
            get {
                return ResourceManager.GetString("NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O-.
        /// </summary>
        public static string ONegative {
            get {
                return ResourceManager.GetString("ONegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O+.
        /// </summary>
        public static string OPositive {
            get {
                return ResourceManager.GetString("OPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients with this Allergy.
        /// </summary>
        public static string PatientAllergies {
            get {
                return ResourceManager.GetString("PatientAllergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients with this Condition.
        /// </summary>
        public static string PatientChronicConditions {
            get {
                return ResourceManager.GetString("PatientChronicConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescriptions.
        /// </summary>
        public static string Prescriptions {
            get {
                return ResourceManager.GetString("Prescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        public static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
    }
}
